### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by ho33ein74** [Ahmetaksungur/aksfileupload#4]
Hi
How to set the default value to be displayed when the page opens?

**Comment by Ahmetaksungur** [comment]
sorry it's not in this version, i will add it in the next version

**Comment by ho33ein74** [comment]
When will the next version be ready?

**Comment by yahaya323** [comment]
Hi 
If i upload file that the MB is more than 3MB, it give error of file exceed the limit.

**Comment by Ahmetaksungur** [comment]
$("#aks-file-upload").aksFileUpload({
    maxSize: "90 GB", // maximum uploaded file size
  });

if maxSize is 3 MB, it gives you a file upload error.

**Comment by yahaya323** [comment]
> $("#aks-file-upload").aksFileUpload({ maxSize: "90 GB", // maximum uploaded file size });
> 
> if maxSize is 3 MB, it gives you a file upload error.

When it more than 3mb that's when it gives error

**Comment by yahaya323** [comment]
![Capture](https://user-images.githubusercontent.com/46170400/150983805-6936a752-11fa-493f-97e2-ac7dacdb598f.PNG)
Check the error !!

**Comment by yahaya323** [comment]
![Capture1](https://user-images.githubusercontent.com/46170400/150984063-3b19e1a7-93b4-4564-8c55-e1b32be0424b.PNG)
Look at this one, the file is small and no error
